[package]
name = "zedless"
version = "1.0.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/zedless.rs"

[dependencies]
anyhow.workspace = true
workspace-hack.workspace = true
